WildFly archetype for blank WAR project
---------------------------------------

[[introduction]]
==== Introduction

This archetype creates a blank WAR project.
It is prepared for running Arquillian unit tests.
Optionally, it can provision a WildFly server.
More details can be found in the file "src/main/resources/archetype-resources/README.txt", which is end-user doc and added to the resulting project.

[[newwildflyversion]]
==== Component dependencies

The versions of all dependencies and plugins that are used by this archetype are configured in the parent's `pom.xml`.

[[build]]
==== Build
To build the archetype, you need at least Java 17. Run this command:
[source,options="nowrap"]
----
$ mvn clean install
----
It will be installed to your local maven repository at "%USERHOME%/.m2/repository/org/wildfly/archetype/wildfly-jakartaee-webapp-archetype/", and an entry will be added to "%USERHOME%/.m2/repository/archetype-catalog.xml".

[[createproject]]
==== Create project from archetype
To create a new project from this archetype, use this maven command (replace dummy values for "groupId", "artifactId" and "version" with correct values):
----
$ mvn archetype:generate -DgroupId=my.project.org -DartifactId=sampleproject -Dversion=1.0-SNAPSHOT -DarchetypeGroupId=org.wildfly.archetype -DarchetypeArtifactId=wildfly-jakartaee-webapp-archetype -DarchetypeVersion=36.0.0.Final-SNAPSHOT
----

[[testing]]
==== Test the archetype
After having built the archetype, check whether all four profiles "arq-remote", "arq-managed", "provision" and "arq-provisioned" work. This is done by using scripts found in the directory "testing".

The four profiles are executed as part of the Github CI.

* Profile "arq-managed": set variable JBOSS_HOME, then execute "runtest_managed.bat/.sh <archetypeVersion>" (replace "<archetypeVersion>" with the current archetype version)
* Profile "arq-remote": start WildFly server, then execute "runtest_remote.bat/.sh <archetypeVersion>" (replace "<archetypeVersion>" with the current archetype version)
* Profile "provision": execute "runtest_provision.bat/.sh <archetypeVersion>" (replace "<archetypeVersion>" with the current archetype version)
* Profile "arq-provisioned": execute "runtest_provisioned.bat/.sh <archetypeVersion>" (replace "<archetypeVersion>" with the current archetype version)

The three "arq-....bat/.sh" files create a project from the archetype (in "testing/arq-managed", "testing/arq-remote", "testing/provision" or "testing/arq-provisioned"),
copy an Arquillian unit test class and an EJB in this project, then build and deploy it to WildFly and execute the test using the Arquillian profile
"arq-managed", "arq-remote" or "arq-provisioned").
After the test is executed, check the server log for error outputs. In case of success, the outputs "Test is invoked..." and "doTest is invoked..." will be printed in the server console.

The "provison.bat/.sh" files just builds the project and provisions a server.
