= WildFly getting started archetype
:toc:

[[introduction]]
== Introduction

This archetype creates a new WAR project which contains a simple Restful web
service and a HTML page to call the web service.

The generated project is configured to dynamically provision a WildFly server
and run the web application on the provisoned server so no manual installation
is required.

It is prepared for running Arquillian unit tests.
More details can be found in the file "src/main/resources/archetype-resources/README.adoc", which is end-user doc and added to the resulting project.

[[newwildflyversion]]
== New WildFly version and dependency updates
The versions of all required dependencies are configured in the archetypes root project. When building the root pom, the file "src/main/resources-filtered/archetype-resources" is
copied to "target/classes/archetype-resources", then all version variables are replaced with the values of the root pom, and the archetype artifact is built.

So, to update this archetype to a new WildFly version, just update the version variables in the root pom, then run a build of the archetype root project.


[[build]]
== Build
To build the archetype, you need at least Java 17. Run this command in the archetype root project:
[source,options="nowrap"]
----
$ mvn clean install
----
It will be installed to your local maven repository at "%USERHOME%/.m2/repository/org/wildfly/archetype/wildfly-getting-started-archetype/", and an entry will be added to "%USERHOME%/.m2/repository/archetype-catalog.xml".

[[createproject]]
== Create project from archetype
To create a new project from this archetype, use this maven command (replace dummy values for "groupId", "artifactId" and "version" with correct values):
----
$ mvn archetype:generate -DgroupId=my.project.org -DartifactId=sampleproject -Dversion=1.0-SNAPSHOT -DarchetypeGroupId=org.wildfly.archetype -DarchetypeArtifactId=wildfly-getting-started-archetype -DarchetypeVersion=36.0.0.Final-SNAPSHOT
----

[[testing]]
== Test the archetype
As part of building the archetype, Maven creates a project "basic" and launches a test run. This test run provisions a WildFly server using WildFly Glow. The sample
war file is added the deployments. Then the server is started and tests are executed. As the archetype contains a "real" service and two test class (server side and client side),
a full arquillian test run is performed during build, so no additional manual testing is required.

